[phases.setup]
nixPkgs = ["nodejs_22", "python3", "gcc", "ghostscript", "poppler_utils", "binutils", "imagemagick"]

[phases.install]
cmds = ["npx --yes n 22.14.0", "hash -r", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node build/index.js"
